export const CATEGORIES = [
  {
    slug: "medical_health",
    name: "Medical & Health",
    description: "Health history, conditions, medications, and wellness practices",
    icon: "heart-pulse",
    subcategories: [
      { slug: "conditions", name: "Conditions & Diagnoses" },
      { slug: "medications", name: "Medications & Treatments" },
      { slug: "family_medical", name: "Family Medical History" },
      { slug: "wellness", name: "Wellness & Prevention" },
      { slug: "mental_health", name: "Mental Health" },
    ],
  },
  {
    slug: "financial",
    name: "Financial",
    description: "Financial wisdom, lessons learned, and practical money advice",
    icon: "banknote",
    subcategories: [
      { slug: "money_lessons", name: "Money Lessons" },
      { slug: "career_financial", name: "Career & Earnings" },
      { slug: "investing", name: "Investing & Savings" },
      { slug: "big_purchases", name: "Big Purchases & Decisions" },
      { slug: "generosity", name: "Generosity & Giving" },
    ],
  },
  {
    slug: "relationships",
    name: "Relationships",
    description: "Friendships, partnerships, and interpersonal wisdom",
    icon: "users",
    subcategories: [
      { slug: "romantic", name: "Romantic Relationships" },
      { slug: "friendships", name: "Friendships" },
      { slug: "family_dynamics", name: "Family Dynamics" },
      { slug: "conflict", name: "Conflict & Resolution" },
      { slug: "community", name: "Community & Belonging" },
      { slug: "mentorship", name: "Mentorship" },
    ],
  },
  {
    slug: "deeply_personal",
    name: "Deeply Personal",
    description: "Private reflections, fears, regrets, and innermost thoughts",
    icon: "lock",
    subcategories: [
      { slug: "fears_anxieties", name: "Fears & Anxieties" },
      { slug: "regrets", name: "Regrets & What-Ifs" },
      { slug: "secrets", name: "Secrets & Confessions" },
      { slug: "dreams_aspirations", name: "Dreams & Aspirations" },
      { slug: "self_reflection", name: "Self-Reflection" },
    ],
  },
  {
    slug: "life_lessons",
    name: "Life Lessons",
    description: "Hard-won wisdom, advice, and things you wish you knew sooner",
    icon: "lightbulb",
    subcategories: [
      { slug: "mistakes", name: "Mistakes & Growth" },
      { slug: "turning_points", name: "Turning Points" },
      { slug: "advice_self", name: "Advice to Younger Self" },
      { slug: "principles", name: "Guiding Principles" },
      { slug: "resilience", name: "Resilience & Overcoming" },
      { slug: "gratitude", name: "Gratitude & Appreciation" },
    ],
  },
  {
    slug: "family_traditions",
    name: "Family & Traditions",
    description: "Family stories, recipes, customs, and cultural heritage",
    icon: "home",
    subcategories: [
      { slug: "family_stories", name: "Family Stories" },
      { slug: "recipes", name: "Recipes & Food" },
      { slug: "customs", name: "Customs & Rituals" },
      { slug: "heritage", name: "Cultural Heritage" },
      { slug: "holidays", name: "Holidays & Celebrations" },
      { slug: "heirlooms", name: "Heirlooms & Objects" },
    ],
  },
  {
    slug: "career_work",
    name: "Career & Work",
    description: "Professional experiences, industry knowledge, and career advice",
    icon: "briefcase",
    subcategories: [
      { slug: "career_path", name: "Career Path & Decisions" },
      { slug: "skills", name: "Skills & Expertise" },
      { slug: "leadership", name: "Leadership & Management" },
      { slug: "workplace", name: "Workplace Experiences" },
      { slug: "entrepreneurship", name: "Entrepreneurship" },
    ],
  },
  {
    slug: "hobbies_interests",
    name: "Hobbies & Interests",
    description: "Passions, creative pursuits, and things that bring joy",
    icon: "palette",
    subcategories: [
      { slug: "creative", name: "Creative Pursuits" },
      { slug: "sports_fitness", name: "Sports & Fitness" },
      { slug: "travel", name: "Travel & Adventure" },
      { slug: "learning", name: "Learning & Education" },
      { slug: "collections", name: "Collections & Hobbies" },
      { slug: "nature", name: "Nature & Outdoors" },
    ],
  },
  {
    slug: "values_beliefs",
    name: "Values & Beliefs",
    description: "Moral compass, faith, philosophy, and what matters most",
    icon: "compass",
    subcategories: [
      { slug: "core_values", name: "Core Values" },
      { slug: "faith_spirituality", name: "Faith & Spirituality" },
      { slug: "philosophy", name: "Philosophy & Worldview" },
      { slug: "ethics", name: "Ethics & Morals" },
      { slug: "purpose", name: "Purpose & Meaning" },
    ],
  },
  {
    slug: "memories_stories",
    name: "Memories & Stories",
    description: "Cherished memories, funny moments, and stories worth preserving",
    icon: "book-open",
    subcategories: [
      { slug: "childhood", name: "Childhood Memories" },
      { slug: "milestones", name: "Milestones & Firsts" },
      { slug: "funny_moments", name: "Funny Moments" },
      { slug: "pivotal_events", name: "Pivotal Events" },
      { slug: "places", name: "Places & Settings" },
      { slug: "people_met", name: "People Who Shaped Me" },
    ],
  },
  {
    slug: "daily_reflection",
    name: "Daily Reflection",
    description: "Open-ended reflections about your day, thoughts, and experiences",
    icon: "sun",
    subcategories: [
      { slug: "today", name: "Today's Reflection" },
    ],
  },
] as const;

export type CategorySlug = (typeof CATEGORIES)[number]["slug"];
